# Learn more → https://github.com/TryGhost/action-deploy-theme#getting-started
name: Deploy Theme
on:
    push:
        branches:
            - master
            - main
            - dl-theme
jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Deploy Ghost Theme
              uses: TryGhost/action-deploy-theme@v1
              with:
                  api-url: http://localhost:2369
                  api-key: 66913bc53dfe76460aaf7d06:c26ff01a6b93f0da3e4b12d4ef8cab9aa2743f7cc79d006445cb00a53f06c157
